# Generated by Django 5.2.8 on 2025-11-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('pasword', models.CharField(max_length=256)),
                ('pasword_test', models.CharField(max_length=256)),
                ('rol', models.CharField(choices=[('seller', 'Seller'), ('customer', 'Customer')])),
            ],
        ),
    ]
